main: ${project.package}.Main
name: ${project.name}

version: ${project.version}
description: ${project.description}
website: ${project.url}

authors:
  - ArtformGames

api-version: 1.16

depend:
  - ArtCore

softdepend:
  - PlaceholderAPI

permissions:
  "togglepvp.use":
    description: "Allows the player to toggle PVP status"
    default: true

commands:
  "TogglePVP":
    description: "Toggle PVP status"
    usage: "/togglepvp"
    permission: "togglepvp.use"
    aliases: [ "pvp" ]